# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SolutionGuide
masthead_title: SolutionGuide
email:
description: >- # this means to ignore newlines until "baseurl:"
  Awesome SolutionGuide!
baseurl: "/solution-guide" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: docs
include:
  - _pages
  - assets/architectures
  - assets/patterns

# Build settings
markdown: kramdown
#theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
kramdown:
  toc_levels: 1..6


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


collections:
  architectures:
    output: true
    permalink: /:collection/:path
  patterns:
    output: true
    permalink: /:collection/:path


defaults:
  - scope:
      path: ""
      type: pages
    values:
      classes: wide
      layout: archive
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: architectures
    values:
      classes: wide
      layout: archive
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: patterns
    values:
      classes: wide
      layout: archive
      sidebar:
        nav: "docs"
